<div id='addForm'>
    <h2>Edit employee</h2>
    <div class ="message">
    <? if (!empty($error)): ?>
        <? foreach ($error->getMsgsArr() as $msg): ?>
            <?=$msg ?><br>
        <? endforeach; ?>
    <?  elseif(!empty($success)): ?>
        <?=$success ?><br>
    <? endif; ?>        
    </div>

    <form action="<?=PRJ_URL?>/employees/edit"  method="POST">
        <input type="hidden" name="id" value="<?=$employee->id?>" >
        <div class ="field"> 
            1)Enter new employee name<br> 
            (required).<br><br> 
            <input type="text" name="formData[name]" <? if (!empty($employee->name)):?> value="<?=$employee->name?>" <? endif; ?> >
        </div>
        <div class ="field"> 
            2)Enter new employee e-mail<br> 
            (required).<br><br> 
            <input type="text" name="formData[email]" <? if (!empty($employee->email)):?> value="<?=$employee->email?>" <? endif; ?> >
        </div>

        <div class="clear"></div>
        <div><input type="submit" value="Edit"></div>

    </form>
    <div><a href="<?=PRJ_URL?>/employees">go to page employees</a></div>
</div>

<div class="clear"></div>
