<html>
<!DOCTYPE html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>:: Simple Boardroom Booker :: </title>
    <link rel="stylesheet" href="<?=CSS_URL?>/main.css" type=text/css />
    <script src="<?=JS_URL?>/main.js"></script>
</head>                     
<body>                  
                     
                     
                     
                     
                     
                     